import { BaseEntity } from './../../shared';

export class Composite implements BaseEntity {
    constructor(
        public id?: number,
        public deviceId?: string,
        public crashDate?: string,
        public latitude?: number,
        public longitude?: number,
        public speed?: number,
        public odometer?: number,
        public heading?: number,
        public rawData?: string,
        public altitude?: number,
        public numberOfSatellites?: number,
        public sequenceNumber?: number,
        public rssi?: number,
        public ntfEngRequestId?: string,
        public crashUuid?: string,
        public deviceIdType?: string,
        public crush?: number,
        public pdof?: number,
        public vin?: string,
        public severityProcessedOn?: string,
        public severityCode?: string,
        public make?: string,
        public model?: string,
        public year?: string,
        public vinRegion?: string,
        public mpd2?: number,
        public mpd3?: number,
        public peakG?: number,
        public deltaV?: number,
        public vehicleClass?: string,
        public createdOn?: string,
        public lastModifiedOn?: string,
        public street1?: string,
        public street2?: string,
        public zip?: string,
        public country?: string,
        public city?: string,
        public stateProvince?: string,
        public crashDirection?: string,
    ) {
    }
}
